### ISSUE TITLE
如何实现微信那种滑动过程中的视差效果呢？

### ISSUE THREAD

**Issue by MIkeeJY** [Jude95/SwipeBackHelper#1]

**Comment by Jude95** [comment]
。。微信哪个界面有滑动关闭了。

**Comment by MIkeeJY** [comment]
微信二级三级页面贴着屏幕左边缘滑动回退啊

**Comment by Jude95** [comment]
微信6.2.4没找到哪个页面有。= =。

**Comment by MIkeeJY** [comment]
微信6.2.2 你试试这个o(￣▽￣)d

**Comment by Jude95** [comment]
看见了。好酷炫(为什么新版本去掉了)。得报持所有activity的引用和栈关系。滑动时。让上层activity的SwipeBackLayout进行跟随位移。。空了就去实现。

**Comment by MIkeeJY** [comment]
目前在git上木有找到实现好的，有一哥们用截图的办法实现的 但是用起来会卡顿

**Comment by Jude95** [comment]
已经实现。

**Comment by MIkeeJY** [comment]
我看下哈~

**Comment by wuyajun7** [comment]
多此点击跳转10个以上的activity就会开始卡顿
