### ISSUE TITLE
滑动返回的时候右侧有明显卡顿

### ISSUE THREAD

**Issue by yuking** [Jude95/SwipeBackHelper#10]

**Comment by Jude95** [comment]
右侧有卡顿？是掉帧还是？另外说说你的机型。

**Comment by yuking** [comment]
你看一下你首页的那个gif演示，有一次和其他的不一样

**Comment by Jude95** [comment]
。。没看出来。调试时对CPU，GPU使用情况也很正常～能再详细一点，什么情况下会卡顿？

**Comment by yuking** [comment]
就是右滑的那块快要完全消失的时候，右侧那里感觉有点卡，不知道这个算不算卡顿，但是微信的就很顺滑
![image](https://cloud.githubusercontent.com/assets/9209701/11140775/3e362dba-8a19-11e5-80d5-895e65dbb3ec.png)

**Comment by Jude95** [comment]
＝ ＝。真心没感觉啊，身边找不到低配置机测试。这个git录的版本还有些bug。右滑快退出屏幕的时候，在执行销毁这个activity与restart下面一个activity。可能会比较耗资源吧。
