### ISSUE TITLE
启动activity的时候没有动画

### ISSUE THREAD

**Issue by 116205035** [Jude95/SwipeBackHelper#11]
微信的开始的时候也是有动画的，而且更加平滑，这个应该还可以优化下，效率上跟微信有差距

**Comment by Jude95** [comment]
作为一个库以非侵入的方式集成是做不到微信的效果。效率上可能是有差距吧，也许是动画不够合适。
用这种方式去定制的话微信的效果可以完美实现。
优化会继续，不过优先级不会太高，现在一堆事忙成狗。╮(╯﹏╰)╭
