### ISSUE TITLE
windowIsTranslucent设置为"true"之后，overridePendingTransition失效

### ISSUE THREAD

**Issue by yangxu4536** [Jude95/SwipeBackHelper#16]
因为必须要把windowIsTranslucent设置为"true"， 当我startActivity同时增加切换动画overridePendingTransition(enterAnim, exitAnim)时， 发现enterAnim有效果，但是exitAnim没有效果，跟微信的还是有区别

**Comment by Jude95** [comment]
作为一个库以非侵入的方式(继承XXActivity)集成是做不到微信的效果。不过你使用
'SwipeBackHelper.getCurrentPage(this).scrollToFinishActivity();'而不是finish，并拦截onBackPress()进行手动关闭就很接近了。
确实不完美，会继续优化的。
