### ISSUE TITLE
 NullPointerException: SwipeBackPage.getSwipeBackLayout() on a null object reference

### ISSUE THREAD

**Issue by 4dcity** [Jude95/SwipeBackHelper#17]
应用场景如下：集成极光推送在app退出后可以接到消息通知。假设当前在某个其他app中，点击通知栏后跳转到自己app的某个activity查看消息详情。此时右滑关闭该acitivy，会报空指针异常。

12-11 14:30:23.138:xxx(8711): java.lang.NullPointerException: Attempt to invoke virtual method 'com.xxx.swipebackhelper.SwipeBackLayout com.xxx.swipebackhelper.SwipeBackPage.getSwipeBackLayout()' on a null object reference
12-11 14:30:23.138: xxx(8711):  at com.xxx.swipebackhelper.RelateSlider.onScrollToClose(RelateSlider.java:47)

定位代码主要是RelateSlider类的public void onScrollToClose()方法，
SwipeBackPage page = SwipeBackHelper.getPrePage(curPage); 
在当前场景下，这里的page = null，之后再调page.getSwipeBackLayout().setX(0);就会报异常了。

目前直接加了一个if(page!=null)的判断，暂时解决问题，其他影响未知。代码没细看，请大神解决。

**Comment by Jude95** [comment]
确实是这样。2.1.5应该没问题了，试试。感谢反馈BUG。
