### ISSUE TITLE
 You Should call SwipeBackHelper.onCreate(activity) first

### ISSUE THREAD

**Issue by ghost** [Jude95/SwipeBackHelper#18]
一直报这个错：
style 设置：
 
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:activityOpenEnterAnimation">@anim/slide_in_right</item>
        <item name="android:activityCloseExitAnimation">@anim/slide_out_right</item>
    </style>
    
    <style name="MainTheme" parent="AppTheme">
        <item name="android:windowIsTranslucent" >false</item>
    </style>
Manifest 设置：
 <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:theme="@style/MainTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

```
            <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>
    </activity>
    <activity android:name=".Main2Activity">
    </activity>
    <activity android:name=".Main3Activity">
    </activity>
</application>
```

and code 只有BaseActivity:如下：
public class BaseActivity extends Activity {

```
@Override
public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState) {
    super.onCreate(savedInstanceState, persistentState);
     SwipeBackHelper.onCreate(this);
    SwipeBackHelper.getCurrentPage(this)
            .setSwipeBackEnable(true)
            .setSwipeSensitivity(0.5f)
            .setSwipeRelateEnable(true)
            .setSwipeSensitivity(1);
}


@Override
protected void onPostCreate(Bundle savedInstanceState) {
    super.onPostCreate(savedInstanceState);
    SwipeBackHelper.onPostCreate(this);
}

@Override
protected void onDestroy() {
    super.onDestroy();
    SwipeBackHelper.onDestroy(this);
}
```

}
一运行就会报题目标的那个错！！求助

**Comment by ghost** [comment]
使用的手机是nexus 5  Android版本：Android5.1.1

**Comment by Jude95** [comment]
你贴的部分代码我看不出有什么错，= =。和demo对比一下吧。
