### ISSUE TITLE
当Activity是个有上下拉的ListView时的冲突解决办法

### ISSUE THREAD

**Issue by ghost** [Jude95/SwipeBackHelper#19]
问题是，当左滑退出的那个Activity是个新闻列表等等，带有上下拉的listview时。下拉变的不灵敏的问题

我在ViewDragHelper的shouldInterceptTouchEvent方法，插入了一个是否是垂直滑动的判断，来解决了。特此告知，建议做下优化。
详情可以看我的博客：http://blog.csdn.net/kimyo8337373/article/details/50372134

**Comment by Jude95** [comment]
呃～你确定这个滑动关闭库有下拉不灵的问题吗。
这个使用的ViewDragHelper是我从头到尾为滑动关闭定制过的，你的博客提及的问题是我2.0解决的问题之一。

**Comment by ghost** [comment]
确定是那样的，主要是下拉的时候，手势如果有偏左或者偏右，就会马上被ViewDragHelper拦截，必须笔直下拉才不会拦截。

**Comment by Jude95** [comment]
＝＝ 只要手势一开始不是横向，后面都不会管。你真的试过我的库吗。
