### ISSUE TITLE
PopupWindow如何处理？

### ISSUE THREAD

**Issue by interchen** [Jude95/SwipeBackHelper#21]
如果在activity中有PopupWindow，会导致activity变成透明的，这种情况要如何处理呢？
如果是把activity的`android:windowIsTranslucent`属性直接设置成false不太好，这样在右滑退出时，前一个activity就不是半透明而是全黑了

**Comment by Jude95** [comment]
能截个图吗

**Comment by interchen** [comment]
看下面的截图，布局在调整，略乱
- 列表界面

![image](https://cloud.githubusercontent.com/assets/2597576/13562937/5d909f74-e478-11e5-9abb-c869a704d314.png)
- 商品详情界面

![image](https://cloud.githubusercontent.com/assets/2597576/13562953/84b074c6-e478-11e5-8b4d-caddd17a184f.png)
- 点击加入购物车，想让用户选择规格，但是使用PopupWindow会有这样的情况

![image](https://cloud.githubusercontent.com/assets/2597576/13562968/a35b78c6-e478-11e5-9cfc-fe056a945d24.png)

**Comment by Jude95** [comment]
你是怎么实现的，为什么Activity会透明。。我测试PopupWindow就很正常啊，在`<item name="android:windowIsTranslucent">true</item>`下。

**Comment by interchen** [comment]
根据你说明，activity的style有一项配置为`<item name="android:windowIsTranslucent">true</item>`

**Comment by Jude95** [comment]
我是说PopupWindow的具体设置。我试试。

**Comment by interchen** [comment]
哎，我知道问题了，是我自己没处理好，真是不好意思

**Comment by yanxinmiao** [comment]
@interchen  到底是什么处理的啊 ？ 劳烦给说说

**Comment by interchen** [comment]
@yanxinmiao 实在想不起来这个问题了，太早了，抱歉

**Comment by AndSync** [comment]
@yanxinmiao 我估计他是在popupwindow或者dialog里面也加透明了，可能会引起这样的效果

**Comment by yanxinmiao** [comment]
```
 @Override
    public void showAtLocation(View parent, int gravity, int x, int y) {
        WindowManager.LayoutParams lp = activity.getWindow().getAttributes();
        lp.alpha = 0.5f;
        activity.getWindow().setAttributes(lp);
        super.showAtLocation(parent, gravity, x, y);
    }
```
弹出时 背景变暗，其他地方也没有透明相关的代码

**Comment by yanxinmiao** [comment]
问题可能是上边 让背景变暗那部分代码造成的，那部分代码改成
```
ColorDrawable dw = new ColorDrawable(0xb0000000);
 setBackgroundDrawable(dw);
```
问题竟然好了 ...
