### ISSUE TITLE
滑动返回的过程 底部是黑色的

### ISSUE THREAD

**Issue by smuyyh** [Jude95/SwipeBackHelper#22]
应该是要显示前一个页面的UI吧？但是在滑动过程中是黑色的，直到完全关闭。在华为pad上

**Comment by Jude95** [comment]
按照Readme的配置部分，配置好了就不会黑。

**Comment by smuyyh** [comment]
貌似没有处理滑动冲突呀~~~

**Comment by Jude95** [comment]
呃~因为ViewPager与RecyclerView都会消费掉所有事件。
如果我等子View处理事件之后再处理自己逻辑，对于RecyclerView纵向布局的界面，我就不能进行事件处理。
现在是在子View之前处理。所以会抢占ViewPager的事件，它将不能响应事件。
这2种相同场景需要不同方式，我没办法1套方案处理。上面是2个典型例子。（如果是ViewPager在RecyclerView中我就要疯了）
现在我的想法想可以做1个配置，切换2种模式。自选。
你有什么好的方案吗？

**Comment by Jude95** [comment]
3.0.1试一试吧。对滑动冲突的处理，我觉得这已经是极限了。
`SwipeBackHelper.getCurrentPage(this).setDisallowInterceptTouchEvent(true);`
false表示强行拦截滑动关闭手势。
true表示放行所有手势给你的View处理，然后捡一些你没有处理的手势来分析进行滑动处理。

**Comment by BochengLiu** [comment]
我的底部也是黑的 和Readme一样配置的 不知道是哪的问题
