### ISSUE TITLE
  <item name="android:windowIsTranslucent">false</item>无效

### ISSUE THREAD

**Issue by lvtanxi** [Jude95/SwipeBackHelper#25]
首先感谢作者解决卡顿的问题。我遇见的问题是在主activity的theme中添加  <item name="android:windowIsTranslucent">false</item>, readme.txt也提到设置了之后就不会滑动退出了。但是我现在是设置了以后依旧滑动退出了。我的手机是小米note以及华为P6

**Comment by Jude95** [comment]
可能readme没写清楚...是需要你再手动关闭可滑动的。@_@

**Comment by BochengLiu** [comment]
求帮助。小米3测试的时候 侧滑退出activity回到主activity的过程中  背景是透明的。 该设置的都设置了。

**Comment by BochengLiu** [comment]
没问题...我的锅
