### ISSUE TITLE
会考虑加上左滑退出吗

### ISSUE THREAD

**Issue by gbdxl** [Jude95/SwipeBackHelper#27]
在查看图片的界面，希望可以在滑到第一张和最后一张图的时候都可以滑动退出

**Comment by Jude95** [comment]
不会考虑。考虑到基本没有左/下/上滑手势处理需求，故意删掉了多方向处理，并针对右滑手势做了大量优化。已经不能支持其他方向了。
你这种需求的交互也是第一次见...查看图片到底了肯定应该划不动啊，单击图片退出。
