### ISSUE TITLE
在沉浸式状态栏的时候

### ISSUE THREAD

**Issue by ybADMIN** [Jude95/SwipeBackHelper#28]
在沉浸式状态栏方式滑动activity出屏幕后状态栏会才跟着移除

**Comment by Jude95** [comment]
你是使用SystemBarTint吧。他用了和我一样的原理。所以我控制不了它。
请使用透明状态栏。http://www.jianshu.com/p/f3683e27fd94/comments/2603505

**Comment by ybADMIN** [comment]
谢谢你的回复
