### ISSUE TITLE
在小米3上会和状态栏填涂冲突，导致状态栏变成白色

### ISSUE THREAD

**Issue by tinybright** [Jude95/SwipeBackHelper#29]
状态栏填涂 com.readystatesoftware.systembartint:systembartint:1.0.3

**Comment by Jude95** [comment]
请发项目地址，我看看源码再看怎么兼容。
另外5.0以后就不建议状态栏填涂了。
建议这样：
http://www.jianshu.com/p/f3683e27fd94

**Comment by tinybright** [comment]
项目地址 https://github.com/jgilfelt/SystemBarTint

5.0 是用的setStatusBarColor不会有什么问题

**Comment by Jude95** [comment]
呃~这个库已经被注明[DEPRECATED] 了。
然后我尝试了6.0和4.4都正常。
是只有小米3有问题吗。
@_@咱能别用这个库了吗。用用上面文章的方法 或者 v7包的FitWindowsXXLayout 或者 CoordinatorLayout 都不错..
