### ISSUE TITLE
2.0.0版本手势事件有bug

### ISSUE THREAD

**Issue by zyyoona7** [Jude95/SwipeBackHelper#3]
设置可滑动范围setSwipeEdge(200)后，如果在200范围之外右滑就会崩，java.lang.IllegalArgumentException: pointerIndex out of range的异常，在范围之内右滑和不设置则没问题

**Comment by dashugege** [comment]
是啊 我也遇到了 你滑动返回  上一级 能看到上一级页面吗？

**Comment by zyyoona7** [comment]
其他的都正常，微信联动也可以

**Comment by Jude95** [comment]
不好意思，测试不到位。现在好了。

**Comment by zyyoona7** [comment]
2.0.1一直引入失败呢？Failed to resolve: com.jude:swipebackhelper:2.0.1。。改成2.0.0没问题

**Comment by Jude95** [comment]
现在好了。。尽然上传失败没注意。

**Comment by chentengming** [comment]
发现了一个bug 在右滑还未松开的时候 这时另一个手指点一下 那么当前的界面就不能退出 漏出一截
