### ISSUE TITLE
配置compile 'com.jude:swipebackhelper:3.1.2'会引入重复的jar包再外部包中有个vector-drawable-23.4.0有两个这样的jar导致冲突，运行时错误，这个怎么破？

### ISSUE THREAD

**Issue by heiyl** [Jude95/SwipeBackHelper#30]

**Comment by heiyl** [comment]
如下是加上compile 'com.jude:swipebackhelper:3.1.2' 后运行时的错误信息，去掉后能正常运行，有空帮忙分析一下呗，谢谢
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.tencent.mm.sdk.b.b) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
Error:Execution failed for task ':transformClassesWithDexForCHANNEL_360_TYPEDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'F:\Program Files\Java1.8\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 2

**Comment by Jude95** [comment]
我可只依赖了com.android.support:appcompat-v7:23.4.0
你可以试试
    compile ('com.jude:swipebackhelper:3.1.2'){
        exclude module: 'appcompat-v7'
    }

**Comment by heiyl** [comment]
这样子就没问题了，谢谢
