### ISSUE TITLE
6.0上 (微信联动效果)，prePage(Activity) 与curPage(Activity)联动之间有间隙，5.1.1上无问题

### ISSUE THREAD

**Issue by andyxialm** [Jude95/SwipeBackHelper#32]
![image](https://cloud.githubusercontent.com/assets/5976556/15843982/0338432e-2c99-11e6-85dc-cb850a8f3812.png)

**Comment by Jude95** [comment]
你是不是setSwipeRelateOffset设得过大了。。一般500左右。或者直接屏幕宽度/3吧

**Comment by andyxialm** [comment]
看到了demo中设置的是800  
已解决
