### ISSUE TITLE
Rtl support?

### ISSUE THREAD

**Issue by mahdimortazavi** [Jude95/SwipeBackHelper#35]
this source can swipe layout to left silde?
This means that unlike in this case,

![device-2016-07-24-200051](https://cloud.githubusercontent.com/assets/10667180/17084681/7df8817c-51d9-11e6-9045-3ad8ba08e1bb.png)

**Comment by Jude95** [comment]
sorry.In order to hand the gesture more accurately.I only considered one direction.Two direction is...so complex.
