### ISSUE TITLE
在android 4.4.4系统上使用出现异常

### ISSUE THREAD

**Issue by szhangbiao** [Jude95/SwipeBackHelper#40]
滑动时阴影部分不是显示上一个页面，而是手机桌面，另外应用在部分手机会发生页面重叠现象，就是页面背景全部面透明了

**Comment by Jude95** [comment]
你增加了 `MIUI特殊处理`的部分吗。
背景透明是肯定的，不然滑动的时候怎么能看到下面的Activity，需要你自己给每个页面设置背景。
你也可以使用
  `<item name="android:colorBackground">@color/colorPrimaryDark</item>`
添加Activity的默认背景。
