### ISSUE TITLE
SwipeBackHelper如何和SystemBarTint一起用？

### ISSUE THREAD

**Issue by zyyoona7** [Jude95/SwipeBackHelper#7]
SwipeBackHelper如何和SystemBarTint一起用？

**Comment by Jude95** [comment]
5.0后statusbar与navigationbar都属于可显示范围。所以不建议使用SystemBarTint。如果要使用...也没什么问题。SwipeBackHelper并不能将StatusBar带着移动。

**Comment by zyyoona7** [comment]
有问题，设置   android:fitsSystemWindows=true   android:clipToPadding=false属性后就被顶到上面了，下面为StatusBar的高度

**Comment by Jude95** [comment]
与SwipeBackHelper这个库有什么关系吗？我没用过SystemBarTint。请描述详细点？

**Comment by zyyoona7** [comment]
已经放弃SystemBarTint，设定了主题了。那个就是在使用SystemBarTint的时候需要在style中设置android:fitsSystemWindows=true android:clipToPadding=false，与SwipeBackHelper一起使用后就会将页面上移，下面留出黑色的和StatusBar高度一样。我猜想是覆盖了，因为滑动过程中可以看到底层页面的StatusBar设置的颜色(我自定义的TitleBar，sytle为NoActionBar)

**Comment by Jude95** [comment]
好吧，我看了SystemBarTint的源码。我的原理是在decorview与他第一个子View中间再插入一个FrameLayout来处理所有手势。对于正常布局是不会有问题的。
但SystemBarTint给decorview添加了一个子View来作为statusbar的背景。
如果他先操作。我就会覆盖他的view。应该就是你这样。
如果我先操作。应该就没什么问题。只是滑动时依然移动不了他的statusbar的填充view。

如果没有问题的话～就关闭这个issue了。

**Comment by zyyoona7** [comment]
应该就是第一种情况了，因为我设置statusbar在SwipeBackHelper前面的。没问题了
