### ISSUE TITLE
Nexus_5_API_23 的情况下，右划底层会黑屏。华为荣耀3X测试正常。

### ISSUE THREAD

**Issue by wudashan** [Jude95/SwipeBackHelper#9]
![image](https://cloud.githubusercontent.com/assets/5417695/11081878/75dc291e-885b-11e5-949a-0f0b833860a6.png)

**Comment by Jude95** [comment]
。。Nexus5X API23 都正常。主题设置没问题吗。是不是value-v21里写了奇怪的东西？

**Comment by wudashan** [comment]
是的..
